spring:
  application:
    name: 4vidia-bookstore-front-test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@discovery-server-test:10465/eureka/